# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Inner product
#'
#' Calculate the inner product of the bin Value Equation 
#' @keywords internal
NULL

#' Find a new division splitting position for the current bin
#'
#' @param bin A matrix containing the whole spectral range.
#'   Cols 0-2  are : bins, bin_start, bin_end, then come samples (col-wise)
#' @param r resolution
#' @param noise noise value
#' @param left,right index of bin_end for the current bin
#'   (C++ index 0 to length-1). 
#' @returns A dbl, the new optimal splitting position or 
#'   NAN if not splitting is possible
#' @keywords internal
NULL

#' Calculate bin value (Vb)
#'
#' @param bin A matrix containing the whole spectral range.
#'   Cols 0-2  are : bins, bin_start, bin_end, then come samples (col-wise)
#' @param r resolution
#' @param noise noise value
#' @param left,right index of bin_end for the current bin
#'   (C++ index 0 to length-1). 
#' @returns A dbl, the bin value
#' @keywords internal
bin_value <- function(bin, r, left, right) {
    .Call(`_tidySpectR_bin_value`, bin, r, left, right)
}

#' Reccursively split the bin 
#'
#' @param bin A matrix containing the whole spectral range.
#'   Cols 0-2  are : bins, bin_start, bin_end, then come samples (col-wise)
#' @param r resolution
#' @param noise noise value
#' @param left,right index of bin_end for the current bin
#'   (C++ index 0 to length-1). 
#' @param indices storage of splitting indices, should be initializied with `right`.
#' @returns A vector of splitting indices 
#' @keywords internal
recc_split <- function(bin, r, noise, left, right, indices) {
    .Call(`_tidySpectR_recc_split`, bin, r, noise, left, right, indices)
}

#' Find the max bin value in the noise region
#' 
#' @param bin A matrix containing the noise region
#'   Cols 0-2  are : bins, bin_start, bin_end, then come samples (col-wise)
#' @param R resolution
#' @returns A dbl, maximum bin value in the noise region
#' @keywords internal
vnoise <- function(bin, r) {
    .Call(`_tidySpectR_vnoise`, bin, r)
}

